### PR TITLE
Initial textshapes functions

### PR DESCRIPTION
**Pull request by cortinah**

### CODE REVIEW

**Comment by aedobbyn** [comment]
This is so awesome! The recursion you use in `triangle_string` is really innovative.

I pulled this in and made [a few initial changes](https://github.com/aedobbyn/multicolor/blob/cc6bfd394cefe9d39a51684be94eed1a538cb52e/R/textshapes.R).

In particular, if the string is longer than the console width, [setting the buffer to 0](https://github.com/aedobbyn/multicolor/blob/cc6bfd394cefe9d39a51684be94eed1a538cb52e/R/textshapes.R#L60). I wasn't sure whether both of the eliminations of the newlines and spaces were necessary so I took them out [here](https://github.com/aedobbyn/multicolor/blob/cc6bfd394cefe9d39a51684be94eed1a538cb52e/R/textshapes.R#L66); if they are, let me know.

For `triangle_string`, what do you think about allowing the user to specify the length of the longest line as well as the shortest and automatically calculate the length of all the lines in between? That will eliminate the way that the last line of the triangle is often shorter than the one before it, e.g. 

```
triangle_string(starwars_intro, display = TRUE) %>% 
  center_string() %>% 
  multi_color(direction = "horizontal", recycle_chars = TRUE)
```

Beyond that, do you have any ideas for how the `<shape>_string` method could be extended to work with any arbitrary shape?

Thanks again for this -- it's great!

**Comment by aedobbyn** [comment]
Sorry @cortinah forgot to tag you here. Even though this was merged and automatically closed, I think we can continue conversation here about the points above, if you have thoughts.

**Comment by cortinah** [comment]
Thank you, no problem, and sorry it's taken me a little time to come back. I think the `<shape>_string` methods could be written out over time, based on shapes that might look interesting. I don't know that it can be easily generalized, each one probably needs to be built on its own, akin to the "geoms" in ggplot2.

The fix on the buffer length looks good.

Regarding the problem with the dangling short last line, that was the reason why I had two eliminations of newlines and spaces.  For a given string input, setting `removelastbreak` to `TRUE` will merge the last short line with the previous line to give you a longer line.  This is indeed a little hackish but it works.  In general the user will have to experiment a bit with `maxlen` and `step` arguments to make a given string look ok.  Feel free of course to make further improvements and happy to help.

Separately, please take a look at the logo branch when you have some time.  Those additions are completely independent of these.  Would like to know if you like the way the logo looks!  Can you guess the color palette used? I've been digging into ASCII art and have found a lot of interesting programatic sources of strings that can be fed into `multi_color()`. There are some other ideas I want to run past you as well.

**Comment by aedobbyn** [comment]
> Regarding the problem with the dangling short last line, that was the reason why I had two eliminations of newlines and spaces. For a given string input, setting removelastbreak to TRUE will merge the last short line with the previous line to give you a longer line. This is indeed a little hackish but it works. In general the user will have to experiment a bit with maxlen and step arguments to make a given string look ok. Feel free of course to make further improvements and happy to help.

Totally, and I see how this is a solid solution. What I'm talking about is creating a way to infer what the best `step` size would be such that the longest line is exactly `maxlen` and the shortest line is `step` characters. That way we could have a `step` = `"auto"` option. I'll have to give this some more thought but it seems like it should be possible.

**Pull request merged**
