### PR TITLE
Allow direction argument to be abbreviated

### PR DESCRIPTION
**Pull request by cortinah**
small patch to allow direction (horizontal or vertical) to be abbreviated and checked.

### CODE REVIEW

**Comment by aedobbyn** [comment]
Hey! I like the check in the first two lines that `direction` is one of the two possible options. 

As for the third line, what do you think the value is in allowing users to supply an integer? Seems cleaner to me to only allow the explicit direction name, but open to ideas.

**Comment by cortinah** [comment]
Hi Amanda, the third line is necessary because pmatch() returns an integer, in this case either a 1 or 2, or an NA.  The third line turns that integer into a string, ("horizontal" or "vertical") which the rest of the code expects.  hope this makes sense.

**Comment by aedobbyn** [comment]
Ahh I see. Any reason not to use `match.arg`?

**Comment by cortinah** [comment]
nope! i'll use that cleaner option instead. thanks

**Comment by aedobbyn** [comment]
Great, thank you!

**Pull request merged**
