### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by cortinah**
Looks great with these changes.  Tweaked help docs a little here to clarify color recycling.

### CODE REVIEW

**Comment by aedobbyn** [comment]
Nice!! This is great. Would you like to be listed as a ctb or aut?

**Comment by cortinah** [comment]
Thank you for asking.  I'm happy either way (aut or ctb).   Here's a DESCRIPTION file field to make it easier for you:

Authors@R: c(
    person("Amanda", "Dobbyn", email = "amanda.e.dobbyn@gmail.com", role = c("aut", "cre")),
    person("Hernando", "Cortina", email = "hch@alum.mit.edu", role = c("aut"),
           comment = c(ORCID = "0000-0001-6790-4870"))   
)

**Comment by aedobbyn** [comment]
Perfect, thanks! Would you want to update the README? I think having a gif in there would be cool.

**Comment by cortinah** [comment]
will do a little later, got an idea :-)

**Pull request merged**
