### PR TITLE
Added initial mc_crawl() function

### PR DESCRIPTION
**Pull request by cortinah**
Displays characters one at a time in color

### CODE REVIEW

**Comment by aedobbyn** [comment]
Thanks for the awesome PR @cortinah!

Couple initial thoughts: 

- we shouldn't need to import all of `stringr` since you're prefixing all `stringr` functions with `stringr::`. So I think [this line](https://github.com/aedobbyn/multicolor/pull/2/files#diff-3c1c3b949fbfb3301fec5513603085c4R3) isn't needed.

- we also need [a check](https://github.com/aedobbyn/multicolor/blob/e4855134738647353a0d8f49f67fb9cb7a169e56/R/multi_color.R#L68) that coloring is possible (it isn't in some environments, like the R GUI), which we have a helper for in [`use_color`](https://github.com/aedobbyn/multicolor/blob/e4855134738647353a0d8f49f67fb9cb7a169e56/R/utils.R#L13). I think if `use_color` is false you could either error informatively or just print the string character by character with no colors attached -- your call.

**Comment by aedobbyn** [comment]
Nice thanks @cortinah !

Check out the [`crawl` branch](https://github.com/aedobbyn/multicolor/tree/crawl). This takes a different approach and adds your color recycling behavior (which I think is cool) to `multi_color` so as to leverage the full potential of `multi_color` instead of using it to color just a single character. (To color individual characters I originally made [`wrap_character`](https://github.com/aedobbyn/multicolor/blob/crawl/R/utils.R#L45) to use inside `crawl`'s for loop, but realized it's probably better to rely on `multi_color` instead.)

The main benefit of using `multi_color` is that recycling isn't necessary, so we don't need to supply a color for each individual character. Check out the [example](https://github.com/aedobbyn/multicolor/blob/crawl/R/crawl.R#L37) which with this new implementation.

Let me know what you think and if I can answer questions.

**Comment by cortinah** [comment]
Thank you @aedobbyn I really like the elegant way in which you got multi-line input to work.  A couple of suggestions:

1) you defined recyle_chars in the arguments of crawl() but I don't see it being used, and thus recycling isn't working.   You may need to add a line such as this:

if (recycle_chars==T) colors <- rep(colors,length.out=stringr::str_length(txt)) right before calling multi_color

2) I don't think the "+1" on the line calling viridisLite::plasma is needed any more the way the function is built.

Looks awesome overall and also runs faster. thanks for the better approach.

**Comment by aedobbyn** [comment]
Good point! I didn't include `recycle_chars` in the call to `multi_color` in `crawl`. It's in there now. Let me know if you spot other improvements!

**Comment by cortinah** [comment]
Closing this pr since changes on the crawl branch.

**Pull request closed without merging**
